### ISSUE TITLE
Enable OpenSearch

### ISSUE THREAD

**Issue by alanorth** [ilri/DSpace#29]
We can use OpenSearch backend in DSpace to provide custom RSS feeds based on OpenSearch queries, ie for certain subject terms like CRPs.  This is useful because we can feed them to FeedBurner to get alerts when new ones are added.

**Comment by alanorth** [comment]
Seems to be working, but I don't know how to search for custom fields.  I think it's only working with titles...

http://dspacetest.cgiar.org/open-search/discover?query=livestock&format=rss

**Comment by alanorth** [comment]
Ah, it seems we can do advanced metadata field searches in the query, like: `query=author:Alan`, or for the crpsubject field:

http://dspacetest.cgiar.org/open-search/discover?query=crpsubject:CLIMATE%20CHANGE,%20AGRICULTURE%20AND%20FOOD%20SECURITY&sort_by=2&format=rss

But it seems to return other stuff which isn't in the CRP... wtf?   Lemme try an `index-discovery -b` to refresh the indexes.

**Comment by alanorth** [comment]
Ok, `subject` seems to work, or at least returns items that have this term in their title:

http://dspacetest.cgiar.org/open-search/discover?query=subject:LIVESTOCK+AND+FISH

Not sure why it does that... and I still haven't found out what the hell it is _actually_ returning when I search for the `crpsubject` field.

**Comment by alanorth** [comment]
Ah, you have to add the searchFilter to the Discovery configuration you're using as your site's default, see: https://github.com/ilri/DSpace/commit/b970a02554b9a6a3e809be3085864299a8233bad

In our case, we're using `homepageConfiguration` config for our site default, which controls the available search filters.  This same config governs which filters are available in OpenSearch.  Now this seems to be working actually:

http://dspacetest.cgiar.org/open-search/discover?query=crpsubject:LIVESTOCK+AND+FISH

**Comment by alanorth** [comment]
Now all I have to figure out is how to get them to be sorted by date added...

**Comment by alanorth** [comment]
This seems to get us items sorted by date, but in ascending order (oldest first):

http://dspacetest.cgiar.org/open-search/discover?query=crpsubject:LIVESTOCK+AND+FISH&format=rss&sort_by=2&rpp=100

We need a way to get descending... I suspect we just add a custom sort_by to the discovery config, and then access it via it's index.  Like if we have four sort_by options, they would be 0, 1, 2, and 3 here.

**Comment by alanorth** [comment]
Ok, this is promising... it's much easier to see the sort order if we massage the results:

```
$ http 'http://dspacetest.cgiar.org/open-search/discover?query=crpsubject:LIVESTOCK+AND+FISH&format=rss&sort_by=2&rpp=50' | grep pubDate | uniq 
<pubDate xmlns="http://apache.org/cocoon/i18n/2.1">Tue, 02 Dec 2014 13:42:17 GMT</pubDate>
<pubDate>Sat, 01 Jan 2005 00:00:00 GMT</pubDate>
<pubDate>Tue, 01 Jan 2008 00:00:00 GMT</pubDate>
<pubDate>Thu, 01 Jan 2009 00:00:00 GMT</pubDate>
<pubDate>Sun, 01 Nov 2009 00:00:00 GMT</pubDate>
<pubDate>Fri, 01 Jan 2010 00:00:00 GMT</pubDate>
<pubDate>Sun, 28 Feb 2010 00:00:00 GMT</pubDate>
<pubDate>Mon, 01 Mar 2010 00:00:00 GMT</pubDate>
<pubDate>Sun, 18 Apr 2010 00:00:00 GMT</pubDate>
<pubDate>Tue, 01 Jun 2010 00:00:00 GMT</pubDate>
<pubDate>Tue, 20 Jul 2010 00:00:00 GMT</pubDate>
<pubDate>Wed, 21 Jul 2010 00:00:00 GMT</pubDate>
<pubDate>Sun, 01 Aug 2010 00:00:00 GMT</pubDate>
<pubDate>Tue, 24 Aug 2010 00:00:00 GMT</pubDate>
<pubDate>Wed, 25 Aug 2010 00:00:00 GMT</pubDate>
```

So `sort_by=2` is definitely sorting by date published, but in descending order.  It seems other valid sorts are 0, 1, and 3, but I don't know where they are defined, or where to define more.  I will just try adjusting the sort order for all discovery searches in `dspace/config/spring/api/discovery.xml`.

**Comment by alanorth** [comment]
Submitted query to dspace-tech mailing list... 

https://www.mail-archive.com/dspace-tech@lists.sourceforge.net/msg27626.html

**Comment by alanorth** [comment]
Ok, this is insane, the sort options are defined in `dspace.cfg` (even when using Discovery), and there is an `order` parameter for OpenSearch!

http://dspacetest.cgiar.org/open-search/discover?query=crpsubject:LIVESTOCK+AND+FISH&format=rss&sort_by=3&order=DESC

This gives us items, sorted by date accessioned.  Note: the RSS output doesn't actually _list_ the accessioned date field, but the items are indeed sorted according to that field!

**Comment by alanorth** [comment]
DSpace 4 deployed on CGSpace, OpenSearch is working there:

https://cgspace.cgiar.org/open-search/discover?query=crpsubject:LIVESTOCK+AND+FISH&format=rss&sort_by=3&order=DESC

We still need to see if this works in Feed Burner, but this issue is addressed.

**Comment by alanorth** [comment]
According to our `dspace.cfg` we want sort_option 2 for published date:

https://cgspace.cgiar.org/open-search/discover?query=crpsubject:LIVESTOCK+AND+FISH&format=rss&sort_by=2&order=DESC

**Comment by tsega** [comment]
@alanorth if you haven't figured it out yet, the problem with the query are the `+` signs there. The `crpsubject` should be put in quotes (single or double). Here is an example:

[https://cgspace.cgiar.org/open-search/discover?query=crpsubject:"LIVESTOCK AND FISH"&format=rss&sort_by=2&order=DESC](https://cgspace.cgiar.org/open-search/discover?query=crpsubject:"LIVESTOCK AND FISH"&format=rss&sort_by=2&order=DESC)

We actually discovered this after searching for half a day and later simply resorting to the good old trial and error approach.  :-) Hope this helps!

**Comment by alanorth** [comment]
The power of a second pair of eyes! Yes, you're right. The quotes aren't necessary, but indeed, the `+` signs tokenize the parameter string instead of adding a space. The spaces simply needed to be URL encoded as `%20`:

https://cgspace.cgiar.org/open-search/discover?query=crpsubject:LIVESTOCK%20AND%20FISH&format=rss&sort_by=2&order=DESC

Good catch. If it makes you feel better I've lost a few days on this over the last year or two. I'm glad I opened up the issue to track it!
