### ISSUE TITLE
Investigate robots.txt versus X-Robots-Tag HTTP header

### ISSUE THREAD

**Issue by alanorth** [ilri/DSpace#35]
Right now we have both robots.txt and `add_header X-Robots-Tag "none";` for DSpace Test... but I don't know which one is respected.  Ideally, on DSpace Test we would block access in robots.txt, but we deploy CGSpace from the same code base, so that's tricky to have different settings.

Maybe we could use robots_test.txt, and redirect those in the nginx vhost for DSpace Test?

**Comment by bram-atmire** [comment]
Robots.txt is definitely still relevant and respected by well behaving bots. I had a look at wikipedia's robots.txt. Based on their example, I made a suggestion for DSpace:

https://github.com/DSpace/DSpace/pull/764

Definitely make sure to include a sitemap. Right now, the cgspace robots.txt doesn't seem to have one:
https://cgspace.cgiar.org/robots.txt

**Comment by alanorth** [comment]
Thanks, @bram-atmire. I was reading some docs the other day and noticed that XMLUI publishes a link to the htmlmap at least:

```
<a class="hidden" href="/htmlmap"> </a>
```

But we do need to have a way of using the same git codebase with two instances of DSpace, ie production and development.  So that's why I was thinking of using `robots.txt` and `robots-test.txt` or something (and using an nginx redirect on the development server).

**Comment by alanorth** [comment]
After reading a bit on [DSpace's SEO documentation](https://wiki.duraspace.org/display/DSDOC4x/Search+Engine+Optimization) I see we have an `/htmlmap` but no `/sitemap`.  Also, we should list the sitemaps in robots.txt.

**Comment by alanorth** [comment]
Ah, fantastic, we actually have both `/htmlmap` and `/sitemap`! And I see your pull request for a better default robots.txt was merged for DSpace 5.0, I'll just cherry-pick that one over to our 4.x branch because it's a major win.

**Comment by alanorth** [comment]
It is safe to use a permissive `robots.txt` followed by a protective `X-Robots-Tag` HTTP Header. [Google's own docs state this](https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag):

```
After the robots.txt file (or the absence of one) has given permission to crawl a page, by default pages are treated as crawlable, indexable, archivable, and their content is approved for use in snippets that show up in the search results, unless permission is specifically denied in a robots meta tag or X-Robots-Tag.
```

So in our case, production will effectively have a permissive `robots.txt` and test will use the same `robots.txt` -- because they are deployed from the same code base -- but set the `X-Robots-Tag`.

**Comment by alanorth** [comment]
I'm going to close this. Both test and production sites are in Google Webmaster Tools, but due to the `X-Robots-Tag: none` on the test server, it is not being indexed! Webmaster Tools says 27,000 sites submitted from the sitemap, but 0 indexed. :)
