### ISSUE TITLE
Update CUA version

### ISSUE THREAD

**Issue by bram-atmire** [ilri/DSpace#52]
https://github.com/ilri/DSpace/blob/4_x-dev/pom.xml#L38

You can change this into:
<cua.version.number>4.2-3.1.4</cua.version.number>

This version bump will address Peter's request regarding contextualized representation of the most popular pages.

**Comment by alanorth** [comment]
:+1:

**Comment by alanorth** [comment]
Finally getting around to testing this, and I note that it's `4.2-3.1.4-0`.
