### ISSUE TITLE
CGSpace OAI doesn't have a Repository Identifier

### ISSUE THREAD

**Issue by alanorth** [ilri/DSpace#57]
For some reason CGSpace doesn't have a repository identifier, but DSpace Test does! See:
- https://cgspace.cgiar.org/oai/request?verb=Identify
- http://dspacetest.cgiar.org/oai/request?verb=Identify

**Comment by Jayakananthan** [comment]
Please check "dspace/config/modules/oai.cfg" configurations in both installation(Test & Live)

**Comment by alanorth** [comment]
Those configs are generated automatically, and the values are interpolated by the maven/ant build scripts.  CGSpace says this, for example:

```
identifier.prefix = cgspace.cgiar.org
# Base url for bitstreams
bitstream.baseUrl = https://cgspace.cgiar.org
```

But for some reason the `Identify` verb doesn't see it... I just checked my local test servers and they all identify fine.  Maybe CGSpace just needs to be re-deployed or something (which we're doing in the next few days anyways). Let's keep an eye on it.

**Comment by alanorth** [comment]
Ok, we re-deployed CGSpace production yesterday and I still don't see an identifier... gotta do more digging.

**Comment by alanorth** [comment]
Wow,! I just fixed this. It turns out we had the OAI application enabled, but the index was empty! I forced a regeneration of the indexes and cleaned the OAI caches and now it should be working!

``` console
$ ionice -c2 -n7 /home/cgspace.cgiar.org/bin/dspace oai import -c -v -o
$ /home/cgspace.cgiar.org/bin/dspace oai clean-cache
```

Closing issue, but you should definitely try it and comment, @Jayakananthan! Check the Identify page again:

https://cgspace.cgiar.org/oai/request?verb=Identify

**Comment by Jayakananthan** [comment]
Hi Alan, I checked again but results failed. I don't know what might be a problem. Anyway I am continuing my testing process and I will let you know anything I found regards this................

**Comment by alanorth** [comment]
@Jayakananthan You're right, it's not working. Well, more specifically, DSpace's OAI is working (it wasn't before), but now we're failing to pass the validation tests.

I just opened a new issue for this #63.
