### ISSUE TITLE
Add IPv6 DNS records

### ISSUE THREAD

**Issue by alanorth** [ilri/DSpace#59]
Our Linode VPSes have IPv6, but we don't have AAAA records, so IPv6 clients have to use IPv4 instead.

**Comment by alanorth** [comment]
Note: if we start using IPv6 then we have to manage the IPv6 firewall rules... need to investigate and integrate into our Ansible playbooks.

**Comment by alanorth** [comment]
Added IPv6 listeners to the nginx vhost template, IPv6 firewall rules, and an AAAA record for DSpace Test:

```
$ dig dspacetest.cgiar.org @8.8.8.8 AAAA

; <<>> DiG 9.9.2-P2 <<>> dspacetest.cgiar.org @8.8.8.8 AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7774
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dspacetest.cgiar.org.          IN      AAAA

;; ANSWER SECTION:
dspacetest.cgiar.org.   299     IN      AAAA    2a01:7e00::f03c:91ff:fe73:6a9

;; Query time: 255 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu May 28 18:20:58 2015
;; MSG SIZE  rcvd: 77
```

Now need to check to see if DSpace has support for IPv6 in the GeoIP module, for example.

**Comment by alanorth** [comment]
I can see requests in the DSpace Test activity log from `::1`... hmmm.

**Comment by alanorth** [comment]
Testing DSpace Test with an IPv6 site validator seems to work.

![screen shot 2016-06-28 at 19 08 19](https://cloud.githubusercontent.com/assets/191754/16423214/d0d038ca-3d63-11e6-83b8-2c877aa86442.png)

Maybe I should just add IPv6 records for CGSpace now.

**Comment by oguya** [comment]
I also need to create IPv6 records for the other linodes too. On a side note, seems like CGNET hasn't added IPv6 records for their DNS servers—which explains the red X—but this shouldn't be a major issue.

**Comment by alanorth** [comment]
Our nginx configs are definitely IPv6 ready (since a year, apparently, according to this issue), but I don't know about your Apache ones?

**Comment by oguya** [comment]
I think they are IPv6 ready. We always, use `<VirtualHost *:80>` which would make apache bind to all addresses assigned to a box. 
So in the case of a cloud VPS instance, apache would serve requests from both IP v4 & v6, provided you have made the necessary firewall changes.

**Comment by alanorth** [comment]
You could `ssh -D` to one of the Linode boxes and then re-direct your Firefox through the SOCKS proxy to test IPv6, since no fucking user ISP has IPv6 to actually test. :)

**Comment by alanorth** [comment]
I'm sitting on a network that uses IPv6 right now and testing DSpace Test (which has been using IPv6 for over a year now). Everything works fine. When we move CGSpace to a new server soon we should just add IPv6 records and be done with this.

**Comment by alanorth** [comment]
Test and production both have IPv6 records now.
