### ISSUE TITLE
Switch to controlled vocabularies

### ISSUE THREAD

**Issue by alanorth** [ilri/DSpace#69]
During research for #34 I found that controlled vocabularies allow you to split up `input-forms.xml` by keeping ILRI subjects, for example, in a separate file. The side effect is that this functionality implies a hierarchical taxonomy, like `ILRI::Subjects::AGRICULTURE` and is stored / displayed in the user interface as such! That requires us to change a lot of the places where we are printing / aggregating subjects in Discovery and XMLUI item lists...

But there is power in this approach! The hierarchy is obviously powerful, and sites like the World Bank's Open Knowledge use it, see `okr.sector` etc:

https://openknowledge.worldbank.org/handle/10986/21529?show=full

This, together with the proper Discovery config is very useful:

https://wiki.duraspace.org/display/DSDOC4x/Discovery#Discovery-Hierarchical(taxonomiesbased)sidebarfacets

**Comment by alanorth** [comment]
One use of this is to be able to get [AGROVOC controlled vocabulary](https://aims-fao.atlassian.net/wiki/display/AGV/Releases) as a drop down list so people could choose from a list of vocabs. AGROVOC does periodic releases that we could process and convert to DSpace's XML value pairs... problems with this include:
- AGROVOC is 22 languages and ~30,000 terms each language!
- The latest release is an RDF/XML file with 17,000,000 lines!

**Comment by alanorth** [comment]
@swebsheet got a basic version of this working for animal breeds. The configuration is cryptic and undocumented, but and it does work. It seems like a hack though, because it relies on omitting the id and label in the controlled vocabulary. Regardless of all other dspace.cfg settings to ignore hierarchy and unsetting the delimiter, if you have an id or label, it will use "Animal breed::BLACKHEAD SOMALI".

Anyways, I'm the only one who will lose sleep over this, as, to the users, it looks like it's working beautifully. The backend is a fucking hack though.

**Comment by swebshet** [comment]
changes from message.xml should be taken to rename Subject Categories link

**Comment by alanorth** [comment]
Latest version of this working code is here: https://github.com/alanorth/DSpace/commit/466563c51256e81b4e8e42e57d778a3233cce978

Also, I don't think we need to rename the "Subject Categories" link—I'd rather remove it entirely, but I don't know how. Anyways, it's not as critical, as it provides the same functionality.

**Comment by swebshet** [comment]
Also `item-view.xsl`:

```
<!-- ANIMAL BREED -->
        <xsl:when test="$clause = 26 and (dim:field[@element='species' and @qualifier='breed'])">
                    <tr class="ds-table-row {$phase}">
                    <td><span class="bold"><i18n:text>Animal breed</i18n:text>:</span></td>
                    <td>
                    <xsl:for-each select="//dim:field[@element='species'and @qualifier='breed']">
                      <xsl:variable name="lnk"><xsl:value-of select="."/></xsl:variable>
                      <a href="/browse?value={.}&amp;type=breed"><xsl:value-of select="."/></a>
                      <xsl:if test="position()!=last()">
                        <xsl:text>, </xsl:text>
                      </xsl:if>
                    </xsl:for-each>
                    </td>
                </tr>
              <xsl:call-template name="itemSummaryView-DIM-fields">
                <xsl:with-param name="clause" select="($clause + 1)"/>
                <xsl:with-param name="phase" select="$otherPhase"/>
              </xsl:call-template>
          </xsl:when>
```

**Comment by alanorth** [comment]
That was already added last week, as it's already working in ANGR, yes?

On Mon, Aug 3, 2015 at 11:55 AM, swebsheet notifications@github.com wrote:

> Also item-view.xsl 
> 
> i18n:textAnimal breed/i18n:text:
> 
> /xsl:variable
> 
> xsl:text, /xsl:text
> /xsl:if
> /xsl:for-each
> 
> /xsl:call-template
> /xsl:when
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ilri/DSpace/issues/69#issuecomment-127168669.

## 

Alan Orth
alan.orth@gmail.com
https://alaninkenya.org
https://mjanja.ch
"In heaven all the interesting people are missing." -Friedrich Nietzsche
GPG public key ID: 0x8cb0d0acb5cd81ec209c6cdfbd1a0e09c2f836c0

**Comment by alanorth** [comment]
We finally started using this for animal breeds in #236. It seems that leaving the `label` blank (but present, or else it causes an error) causes it to be a flat hierarchy. The values are just stored as is in the field.

We also want to do controlled vocabularies for these fields:
- [x] dc.title.jtitle (moved to dc.source in 2016-07)
- [x] dc.contributor.affiliation
- [x] dc.description.sponsorship
- [x] dc.srplace.subregion
- [x] dc.Species

**Comment by alanorth** [comment]
Controlled vocabularies for sponsorship, subregion, and animal breed. Still cleaning up the values for the others.

**Comment by alanorth** [comment]
Added new controlled vocabulary for `cg.contributor.affiliation` in #267.
